vich_uploader:
    db_driver: orm

    mappings:
        media_file:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/uploads'
            namer: Vich\UploaderBundle\Naming\HashNamer
